### ISSUE TITLE
Fails to Install on FreeBSD 12-STABLE

### ISSUE THREAD

**Issue by pprocacci** [salortiz/NativeLibs#10]
%	zef install -v .
===> Testing: NativeLibs:ver<0.0.7>:auth<github:salortiz>
[NativeLibs] t/01-basic.t ........ ok
[NativeLibs] t/02-cannon-name.t .. 
[NativeLibs] Dubious, test returned 255 (wstat 65280, 0xff00)
[NativeLibs] Failed 10/10 subtests 
[NativeLibs] t/10-search.t ....... ok
[NativeLibs] t/20-compile.t ...... ok
[NativeLibs] Test Summary Report
[NativeLibs] -------------------
[NativeLibs] t/02-cannon-name.t (Wstat: 65280 Tests: 0 Failed: 0)
[NativeLibs]   Non-zero exit status: 255
[NativeLibs]   Parse errors: Bad plan.  You planned 10 tests but ran 0.
[NativeLibs] t/10-search.t     (Wstat: 0 Tests: 3 Failed: 0)
[NativeLibs]   TODO passed:   3
[NativeLibs] Files=4, Tests=27,  3 wallclock secs ( 0.05 usr  0.02 sys +  5.52 cusr  0.47 csys =  6.06 CPU)
[NativeLibs] Result: FAIL
===> Testing [FAIL]: NativeLibs:ver<0.0.7>:auth<github:salortiz>
Aborting due to test failure: NativeLibs:ver<0.0.7>:auth<github:salortiz> (use --force-test to override)

**Comment by finanalyst** [comment]
This failure also happens using a docker version of Raku that is provided by JJ.
You have commited a PR by JJ recently, but not bumped the version number. 
I use LibCurl which depends on NativeLibs.
see below for the Travis CI failure script:

 docker pull jjmerelo/test-perl6

116.88s$ docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6

This is Rakudo version 2020.01 built on MoarVM version 2020.01.1

implementing Perl 6.d.

===> Searching for missing dependencies: Template::Mustache, URI, LibCurl, Pod::Load, File::Temp, Test::Output, Test::META, Test::Deeply::Relaxed

===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json

===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json

===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json

===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json

===> Searching for missing dependencies: NativeLibs:ver<0.0.7>:auth<github:salortiz>, JSON::Fast, Test::When, META6, License::SPDX, File::Directory::Tree

===> Searching for missing dependencies: JSON::Class:ver<0.0.14+>, JSON::Class:ver<0.0.5+>

===> Searching for missing dependencies: JSON::Marshal:ver<0.0.18+>, JSON::Unmarshal:ver<0.08+>

===> Searching for missing dependencies: JSON::Name

===> Testing: NativeLibs:ver<0.0.7>:auth<github:salortiz>

[NativeLibs] /bin/sh: gcc: not found

[NativeLibs] The spawned command 'gcc -c -fPIC -Wextra -Wall -Wno-unused-parameter -Wno-unused-function -Wno-missing-braces -Werror=pointer-arith -O3 -DNDEBUG  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=2 -o foo.o foo.c' exited unsuccessfully (exit code: 127, signal: 0)

[NativeLibs]   in method compile-all at /root/.zef/store/NativeLibs.git/511e9eba26b97810c4b2798ceb375761f85aea1d/lib/NativeLibs.pm6 (NativeLibs) line 150

[NativeLibs]   in block <unit> at t/20-compile.t line 12

===> Testing [FAIL]: NativeLibs:ver<0.0.7>:auth<github:salortiz>

Aborting due to test failure: NativeLibs:ver<0.0.7>:auth<github:salortiz> (use --force-test to override)

The command "docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6" exited with 1.

**Comment by salortiz** [comment]
@finanalyst 

The failure you are reporting seems unrelated to the one reported by the OP, that is failing in `t/02-cannon-name.t` simply because the isn't tests for the FreeBSD case.

Yours is in `t/20-compile.t` because that test needs a working gcc compiler not present in @JJ's Docker image.

**Comment by JJ** [comment]
That has changed in the latest installments; since 2020.07 every image does include gcc. Can you please try again now?

**Comment by JJ** [comment]
Ah, also test-perl6 is deprecated; [`raku-test`](https://hub.docker.com/repository/docker/jjmerelo/raku-test) should be used instead.

**Comment by pprocacci** [comment]
https://github.com/salortiz/NativeLibs/pull/11 ... fixes the installation problem on FreeBSD.

**Comment by salortiz** [comment]
Thanks @pprocacci for your PR.
Fixed in v0.0.8
