### ISSUE TITLE
The examples in the readme should use `{*}` instead of `{ * }`

### ISSUE THREAD

**Issue by MasterDuke17** [salortiz/NativeLibs#9]
`{*}` is a single token and the correct thing to use. `{ * }` just happens to work if it's all there is, but if you add other code it won't work.

**Comment by salortiz** [comment]
@MasterDuke17

I think that you are confusing two different things. 

In every sub **the body** should be enclosed by curly brackets (braces), and can have any amount of white-space around them.

The lone star (the `*` token, a `Whatever` object) in `sub foo is native { * }` **is** the body content, common practice in `is native` subs because the actual body doesn't matter. See https://docs.raku.org/language/nativecall.
 
Nothing to do with the single token `{*}` **inside the body** of a `proto` sub or method **used to mark** the dispatch point for the `multi` subs.

Regards.

**Comment by MasterDuke17** [comment]
Hm, that doc page uses both. It really should mention what you just said. I'll create an issue there.
